### ISSUE TITLE
UnicodeEncodeError with Python 2.7

### ISSUE THREAD

**Issue by superdyoll** [Adimote/Southampton_Timetable_Conversion#5]
When running the script with Python 2.7 after saving the timetable and pressing enter I got the following error message:

```
Traceback (most recent call last):
  File "timetable_converter.py", line 317, in <module>
    main()
  File "timetable_converter.py", line 314, in main
    user_interface()
  File "timetable_converter.py", line 297, in user_interface
    cal_file.write(export_as_ical(lectures).replace(r'\n', '\r\n'))
  File "timetable_converter.py", line 250, in export_as_ical
    day_string=day_to_iso_day(lecture["day"])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 19: ordinal not in range(128)
```

**Comment by Adimote** [comment]
Fixed in de205efca50306fddcbcb13a32c4fd1a88050d4e
